python -u src/train.py \
    --is_training 1 \
    --model_id "LSTM_HAR_supcontrastive_finetune_gs_lr1_s101112" \
    --seed 101112 \
    --model "LSTM" \
    --dataset "HAR" \
    --batch_size 32 \
    --max_clip_length 8 \
    --num_nodes 9 \
    --input_dim 16 \
    --output_dim 16 \
    --n_epochs 80 \
    --early_stop 15 \
    --n_classes 6 \
    --plot_epoch 20 \
    --learning_rate 11e-4 \
    --weight_decay 1e-4 \
    --use_gpu True \
    --gpu "cuda:0" \
    --pretrain_model "LSTM_Pred" \
    --pretrain_model_path "LSTM_HAR_SSL_supcontrastive_gs_final_LSTM_test" \
    --fine_tune \