python -u src/train.py \
    --is_training 1 \
    --model_id "LSTM_Heart_gs" \
    --seed 123 \
    --model "LSTM" \
    --dataset "Heartbeat" \
    --task "Detection" \
    --batch_size 32 \
    --max_clip_length 9 \
    --num_nodes 61 \
    --input_dim 45 \
    --hidden_dim 4 \
    --num_rnn_layers 2 \
    --n_epochs 100 \
    --plot_epoch 100 \
    --early_stop 80 \
    --n_classes 1 \
    --learning_rate 2e-3 \
    --weight_decay 0e-5 \
    --use_gpu True \
    --gpu "cuda:1" \

